# Зарегать переменные NEXUS_REGISTRY NEXUS_LOGIN NEXUS_PASSWORD NEXUS_PATH SECRET_NAME  NAMESPACE STAND BASE_IMAGE

image: docker:stable
services:
  - name: docker:dind
    command:
      - "--insecure-registry=registry.x5.phoenixit.ru"

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay2
#  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE: "${NEXUS_REGISTRY}/${NEXUS_PATH}/${CI_PROJECT_NAME}"
  CONFIG_NAME: ${CI_PROJECT_NAME}-config
  SECRET_NAME: ${CI_PROJECT_NAME}-secret

stages:
  - build
  - containerize
  - deploy

before_script:
  - export GRADLE_USER_HOME=/home/gradle/project

build:
  image: gradle:jdk11
  stage: build
  script:
#    - ./gradlew build
     - gradle clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master

package:
  stage: containerize
  before_script:
    - docker login -u $NEXUS_LOGIN -p $NEXUS_PASSWORD $NEXUS_REGISTRY
  script:
    - echo "FROM ${BASE_IMAGE}" >  Dockerfile_tmp
    - grep -v "FROM" Dockerfile >> Dockerfile_tmp
    - cp Dockerfile_tmp Dockerfile
    - docker build --pull -t ${IMAGE}:${CI_COMMIT_SHA:0:8} .
    - docker tag ${IMAGE}:${CI_COMMIT_SHA:0:8} ${IMAGE}:latest
    - docker push ${IMAGE}:${CI_COMMIT_SHA:0:8}
    - docker push ${IMAGE}:latest
    - docker rmi ${IMAGE}:${CI_COMMIT_SHA:0:8}
    - docker rmi ${IMAGE}:latest
  when: manual
  only:
    - master

deploy_test:
  stage: deploy
  variables:
  image: openshift/origin-cli
  script:
    - oc login ${OKD_URL} --token=${OKD_TOKEN} --insecure-skip-tls-verify
    - oc project ${NAMESPACE}
#    - oc create configmap ${CI_PROJECT_NAME}-config --from-file=env/config_${STAND}.yml --dry-run -o yaml | oc apply -n ${NAMESPACE} -f -
    - oc delete configmap ${CONFIG_NAME} --ignore-not-found -n ${NAMESPACE}
    - oc apply -f ci/config_${STAND}.yml -n ${NAMESPACE}
    - oc process -f ci/service.yml NAME=${CI_PROJECT_NAME} IMAGE="${NEXUS_REGISTRY}/${NEXUS_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA:0:8}" NAMESPACE=${NAMESPACE} CONFIG_NAME=${CONFIG_NAME} SECRET_NAME=${SECRET_NAME} | oc apply -n ${NAMESPACE} -f -
#    - oc tag ${IMAGE}:${CI_COMMIT_SHA:0:8} ${CI_PROJECT_NAME}:latest
  when: manual
  only:
    - master
