server:
  port: ${TOMCAT_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

spring:
  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: "jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}"
  liquibase:
    change-log: "classpath:db/changelog/db-master-changelog.xml"
    user: ${PG_USER}
    password: ${PG_PASSWORD}
    url: "jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}"
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info']

security-enabled: ${ENABLE_SECURITY:true}

security:
  oauth2:
    resource:
      jwt:
        key-value: ${PUBLIC_KEYCLOAK_KEY:-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqIqaePXrGqr6x9ndLworFfhRtgxyIhrxKDs1/0uraFyoJrWYR9jMaB/D3l0JjL4Gj5tMsc+zY35DjATDGih4GGIZgVktutCaawn8BvYV3WpyWQCE3VUysuL6gvDRR8BWQ/A8yS8P6iyImS/X3kVJRM+NnCAHdHrI3usgPY4wlP0IFflvJRuZKHDD5EpTz3HSltBer9Q0OBwX4K1eCKPFPsp/aEaNee9SBn1vktAZ6S5ZDyx2jkR6RNjAr57cY9AUqWVfg6WIeeDUcbn6q3B7SSmjVCEGob8sltPPZsertDx6FYoU0Mr+Sb/4+IBFOdubJ5gOxiFNSMvJmdjUX51vkwIDAQAB-----END PUBLIC KEY-----}

user:
  position-id: ${EMPOWERED_POSITION_ID}

interval:
  days: ${INTERVAL_DAYS_FOR_CLOSED_SHOP}

log:
  integration-request:
    enable: ${PAYLOAD_VIEW_ENABLE:true}