apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dss-gateway-config
data:
  CORS_ALLOWED: 'true'
  SECURITY_ENABLED: 'false'
  KEYCLOAK_CLIENT_NAME: 'dss-gateway'
  INTEGRATION_URL: 'http://dss-integration:8080'
  DOCUMENTS_URL: 'http://dss-documents:8080'
  BINDINGS_URL: 'http://dss-bindings:8080'
  REPORTS_URL: 'http://dss-reports:8080'
  JAVA_TOOL_OPTIONS: >
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.profiles.active=production
    -Xms100M
    -Xmx1024M
