apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dss-bindings-config
data:
# in secret   PG_USER:
# in secret   PG_PASSWORD:
  PG_HOST: "MSK-DPRO-PSG146"
  PG_PORT: "5432"
  PG_DATABASE: "docsign"
  SECURITY_ENABLED: 'false'
  KAFKA_URL: "MSK-DPRO-APL241.x5.ru:9093"
  KAFKA_CONSUMER_GROUP_ID: "bindings-group"
  KAFKA_INBOX_BINDINGS_TOPIC: "topic-bindings"
  KAFKA_INBOX_STORES_TOPIC: "topic-stores"
  KAFKA_SSL_ENABLE: "true"
  KAFKA_KEY_STORE_PATH: "/kafka_cert/kafka.x5.keystore.jks"
  KAFKA_TRUST_STORE_PATH: "/kafka_cert/kafka.x5.truststore.jks"
  PUBLIC_KEYCLOAK_KEY: "-----BEGIN RSA PUBLIC KEY-----MIIBCgKCAQEAjNHowuOeS91PsmQmr/geqVyztt1cWw5Wl4S6jRvRFQcg3Ozt17rUe49+NWPv8ooZMIDUBcUSxFJCOOyQ18OPohXRKkU4lnop9XNuXgUVYHSfmZJyDR2Y6pxTdJbxhbEIVUJLYbfdiiH3uo4XHPxRXaSWKg39j9eX6HSEpULcoM3OOaKyowtMUpRSASmupuiL79ewOTEVcBh9irhIn3P2W9ejs5sMLXGD1yrNJUZkDYhoqmcUrYtjemmFqkeouEORRgwpp+CcaIZRZS92A0B1rqaaXVKLUU4uYLYjOj2nQ4LX2csydpIWByd3lE3AF815tfTGzpYvJH1juevrVg9IswIDAQAB-----END RSA PUBLIC KEY-----"
# in secret  KAFKA_KEY_STORE_PASSWORD:
# in secret KAFKA_TRUST_STORE_PASSWORD:
  JAVA_TOOL_OPTIONS: >
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.profiles.active=production
    -Xms100M
    -Xmx1024M
