apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dss-bindings-config
data:
  MONGODB_HOST: "MSK-DPRO-MNG004"
  MONGODB_PORT: "27017"
  MONGODB_DB_NAME: "markus"
  MONGODB_AUTH_DB: "markus"
  GRIDFS_DB_NAME: "markus"
# in secret MONGODB_USER:
# in secret MONGODB_PASSWORD:
  KAFKA_URL: "MSK-DPRO-APL241:9093"
  KAFKA_CONSUMER_GROUP_ID: "documents-group"
  KAFKA_INBOX_DOCS_TOPIC: "topic-inbox-documents"
  KAFKA_SAVE_SIGNED_TOPIC: "topic-save-signed"
  KAFKA_OUTBOX_STATUS_TOPIC: "topic-outbox-status"
  KAFKA_DOCUMENT_EVENTS_TOPIC: "topic-document-event"
  KAFKA_SIGN_RESULT_TOPIC: "topic-sign-result"
  KAFKA_SSL_ENABLE: "true"
  KAFKA_KEY_STORE_PATH: "/kafka_cert/kafka.x5.keystore.jks"
  KAFKA_TRUST_STORE_PATH: "/kafka_cert/kafka.x5.truststore.jks"
# in secret  KAFKA_KEY_STORE_PASSWORD:
# in secret KAFKA_TRUST_STORE_PASSWORD:
  JAVA_TOOL_OPTIONS: >
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.profiles.active=production
    -Xms100M
    -Xmx1600M
