apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dss-bindings-config
data:
# in secret   PG_USER:
# in secret   PG_PASSWORD:
  PG_HOST: "services.x5.phoenixit.ru"
  PG_PORT: "5432"
  PG_DATABASE: "docsign"
  SECURITY_ENABLED: 'false'
  KAFKA_URL: "services.x5.phoenixit.ru:9093"
  KAFKA_CONSUMER_GROUP_ID: "bindings-group"
  KAFKA_INBOX_BINDINGS_TOPIC: "topic-bindings"
  KAFKA_INBOX_STORES_TOPIC: "topic-stores"
  KAFKA_SSL_ENABLE: "true"
  KAFKA_KEY_STORE_PATH: "/kafka_cert/kafka.client.keystore.jks"
  KAFKA_TRUST_STORE_PATH: "/kafka_cert/kafka.client.truststore.jks"
# in secret KAFKA_KEY_STORE_PASSWORD:
# in secret KAFKA_TRUST_STORE_PASSWORD:
  JAVA_TOOL_OPTIONS: >
    -Djava.security.egd=file:/dev/./urandom
    -Dspring.profiles.active=production
    -Xms100M
    -Xmx1024M
