apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dss-bindings-config
data:
  PG_HOST: "MSK-DPRO-PSG154"
  PG_PORT: "5432"
  PG_DATABASE: "docsign"
  ENABLE_SECURITY: 'true'
  KAFKA_URL: "msk-dpro-apl280.x5.ru:9093,msk-dpro-apl281.x5.ru:9093,msk-dpro-apl282.x5.ru:9093"
  KAFKA_CONSUMER_GROUP_ID: "bindings-group"
  KAFKA_INBOX_BINDINGS_TOPIC: "topic-bindings"
  KAFKA_INBOX_STORES_TOPIC: "topic-stores"
  KAFKA_SSL_ENABLE: "true"
  KAFKA_KEY_STORE_PATH: "/kafka_cert/kafka.x5.keystore.jks"
  KAFKA_TRUST_STORE_PATH: "/kafka_cert/kafka.x5.truststore.jks"
  LOG_LEVEL: 'INFO'

# in secret PG_USER:
# in secret PG_PASSWORD:
# in secret KAFKA_KEY_STORE_PASSWORD:
# in secret KAFKA_TRUST_STORE_PASSWORD:
# in secret PUBLIC_KEYCLOAK_KEY:
